### ISSUE TITLE
真搞不定了。 不知道是啥问题

### ISSUE THREAD

**Issue by zyleafhk** [Xmarmalade/alisthelper#10]
### 软件期望的结果是什么？

挂载阿里云盘从成功到失败，没有做任何改动。 就再也连不上了。 

### 实际发生了什么？

头天调试好了Alist+阿里云盘+Rclone，在Macos 上正常挂载 ，也试了用Finder中的“链接服务器功能”+webdav连接‘alist’。 均成功获取到aliyunpan的内容。 
但第二天早上，就再也无法连接Alist, 显示：获取设置失败：请稍候，正在加载储存
<img width="644" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/102453280/0ce85db7-24a7-4268-9bf8-8e72a12aa037">
 重装alist，alisthelper都无法解决。 

手工登录管理界面后，原先显示成功的“存储”配置处，显示：Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)。
手工删除再按原来步骤重新添加也还是同样报错。 

### 您运行的是我们的哪个版本的软件？

3.18.0

### 平台信息

macOS Ventura  版本13.4

### 附加信息

```shell
Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
你好，根据你提供的信息，这可能是alist本身的问题，建议你前往alist相关社区讨论
