### ISSUE TITLE
关于使用新版本添加工作目录闪退问题

### ISSUE THREAD

**Issue by Francis-thpeng** [Xmarmalade/alisthelper#13]
### 软件期望的结果是什么？

成功添加alist并成功启动

### 实际发生了什么？

添加alist工作目录，引发alisthelper闪退

### 您运行的是我们的哪个版本的软件？

0.1.1

### 平台信息

Windows 11 专业版

### 附加信息

```shell
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎9/‎28
操作系统版本	22621.1848
体验	Windows Feature Experience Pack 1000.22642.1000.0
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
这可能和[flutter_file_picker](https://github.com/miguelpruivo/flutter_file_picker)的有关，我会暂时尝试降级依赖来修复这个问题 https://github.com/miguelpruivo/flutter_file_picker/issues/1297

**Comment by Xmarmalade** [comment]
我尝试调整依赖，但是似乎没有效果。如果需要，你可以先自行填写地址，这个问题可能需要进一步研究

**Comment by Xmarmalade** [comment]
迁移至 file_selector: ^1.0.0 解决了问题 https://pub.dev/packages/file_selector
