### ISSUE TITLE
支持rclone以便挂载到本地

### ISSUE THREAD

**Issue by earthjasonlin** [Xmarmalade/alisthelper#15]
### 这是一个什么样的功能？

能否增加一个功能，指定rclone可执行文件，通过rclone将alist挂载为本地磁盘

### 这个功能可以解决什么问题？

-

### 额外描述

已在爱发电赞助

### 这不是重复的功能请求或与 Alist Helper 本身无关的功能请求。

- [X] 我已经搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues)，以确保这不是一个重复的功能请求或与Alist Helper本身无关的功能请求。

### 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

- [X] 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

**Comment by Xmarmalade** [comment]
会在后续版本尝试添加此功能，另外感谢你的赞助

**Comment by earthjasonlin** [comment]
谢谢

**Comment by Xmarmalade** [comment]
经过我对rclone的初步评估，目前方案是单独使用一个页面作为管理rclone的界面，最终效果待定
![image](https://github.com/Xmarmalade/alisthelper/assets/16839488/54c62cc7-79d8-41c4-b0f9-d37080934557)

**Comment by earthjasonlin** [comment]
有没beta体验体验/斜眼笑

**Comment by Xmarmalade** [comment]
> 可以的，有没beta体验体验/斜眼笑
关于新版本：alisthelper处于积极开发中，你可以通过在本地编译源代码获取最新版本，如要获取尚未同步至GithHub的版本，请考虑赞助
下面是一个rclone挂载webdav的实例，仅供参考
![image](https://github.com/Xmarmalade/alisthelper/assets/16839488/906fc14c-b967-4293-95ea-35c82b878073)

**Comment by earthjasonlin** [comment]
> > 可以的，有没beta体验体验/斜眼笑
> 
> 关于新版本：alisthelper处于积极开发中，你可以通过在本地编译源代码获取最新版本，如要获取尚未同步至GithHub的版本，请考虑赞助 下面是一个rclone挂载webdav的实例，仅供参考 ![image](https://user-images.githubusercontent.com/16839488/256490541-906fc14c-b967-4293-95ea-35c82b878073.png)

额，那就是赞助的还不够多吗？那顺便再问一个问题，赞助一次这些权益管多久啊

**Comment by Xmarmalade** [comment]
> > > 可以的，有没beta体验体验/斜眼笑
> > 
> > 
> > 关于新版本：alisthelper处于积极开发中，你可以通过在本地编译源代码获取最新版本，如要获取尚未同步至GithHub的版本，请考虑赞助 下面是一个rclone挂载webdav的实例，仅供参考 ![image](https://user-images.githubusercontent.com/16839488/256490541-906fc14c-b967-4293-95ea-35c82b878073.png)
> 
> 额，那就是赞助的还不够多吗？那顺便再问一个问题，赞助一次这些权益管多久啊

通常提交至GitHub主分支的代码一般会比发行版更新一些，包含了最新的代码，并且通常不存在较大的问题，你可以自行编译，若存在环境等问题导致无法编译且希望获取和主分支同步时，你可以通过赞助获取由我编译的版本，另外你也可以获取正在开发的版本，但是可能存在影响使用的bug。

除了个人技术支持和定制需求以外，其他权益是永久的

**Comment by earthjasonlin** [comment]
那请你有空push一下呗，这也没东西可以编译啊（ᗜ ‸ ᗜ）

**Comment by Xmarmalade** [comment]
最终选择单实例方案
![image](https://github.com/Xmarmalade/alisthelper/assets/16839488/ba78e638-cfd0-4687-a272-fe4a02bd8125)

**Comment by earthjasonlin** [comment]
> 经过我对rclone的初步评估，目前方案是单独使用一个页面作为管理rclone的界面，最终效果待定 ![image](https://user-images.githubusercontent.com/16839488/255852925-54c62cc7-79d8-41c4-b0f9-d37080934557.png)

这个挺好的啊，可以分盘挂

**Comment by earthjasonlin** [comment]
rclone二进制文件放在哪里呢

**Comment by Xmarmalade** [comment]
原有的方案在状态管理上存在一些问题，效果比较差

**Comment by earthjasonlin** [comment]
这样的话是不是一个alist helper只能挂载一个盘了？那是否可以默认启动参数那里就直接默认挂载/到Z:呢

**Comment by Xmarmalade** [comment]
启动参数建议自行测试后填入
`rclone mount remote:path/to/files path/to/mount`
如果你要是挂阿里云之类的需要加一些参数

**Comment by earthjasonlin** [comment]
就是默认嘛，现在是调出webgui。
那还得自己rclone config？不然这个集成进rclone设置里呗，webdav地址是固定的，用户名密码留个文本框

**Comment by Xmarmalade** [comment]
我认为没必要，rclone配置一次不会超过一分钟

**Comment by earthjasonlin** [comment]
或者是......加个按钮“配置rclone”，然后程序运行rclone config？

**Comment by Xmarmalade** [comment]
由于alist 3.25.0 [加密了密码](https://alist.nn.ci/guide/install/script.html#get-password)，故不会再考虑此功能，
但是我找到了先前导致状态管理问题的因素，可能会增加rclone多实例

**Comment by Xmarmalade** [comment]
已添加多盘符挂载
