### ISSUE TITLE
[Enhancemment] Add alist downloader and auto updater

### ISSUE THREAD

**Issue by Xmarmalade** [Xmarmalade/alisthelper#16]

**Comment by LSP0123** [comment]
@Xmarmalade 检测到当前使用的版本为最新版本时，升级按钮仍保持原样，有一定误解。
![image](https://github.com/Xmarmalade/alisthelper/assets/31061624/12922295-294c-4244-bfe9-f559e312bf6c)

建议在版本相同时“升级”字样改为“查看发布页面”，并打开浏览器跳转至项目页面或release页面

**Comment by Xmarmalade** [comment]
这是目前计划的修改方案：提供“打开发布页面”“检查更新”和“下载安装“三个选项
![image](https://github.com/Xmarmalade/alisthelper/assets/16839488/7e6e01f3-93f6-4ad2-9d98-79bfeb950584)
下载会检查更新并询问需要下载的文件，alist会自尝试动安装，alisthelper会下载至默认的下载文件夹中
![image](https://github.com/Xmarmalade/alisthelper/assets/16839488/10c69c2c-f96d-425e-bf86-5f048970d45d)
