### ISSUE TITLE
工作目录为相对路径，自启动时不能启动 alist 主程序，双击启动时正常。

### ISSUE THREAD

**Issue by takenusername** [Xmarmalade/alisthelper#17]
### 软件期望的结果是什么？

alist.exe 启动

### 实际发生了什么？

alist.exe 未启动

### 您运行的是我们的哪个版本的软件？

当前最新

### 平台信息

win11

### 附加信息

```shell
工作目录设置为相对路径 “.\” 以便携化，自启动时不能启动 alist.exe 主程序，双击启动时正常。
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
所有的配置文件都存储在本机ApplicationSupport文件夹中，如果在不同设备上运行，建议单独进行配置
