### ISSUE TITLE
Mac m芯片升级新版本0.1.3，替换的时候，出现闪退问题

### ISSUE THREAD

**Issue by PANPINGLI** [Xmarmalade/alisthelper#22]
### What is expected?

删除重新安装问题依旧存在
我把alist都删除，活动监视器中未找到进程

### What is actually happening?

Mac m芯片升级新版本0.1.3，替换的时候，出现闪退问题

### What version of our software are you running?

0.1.3

### Platform information

mac mini m2

### Additional info

```shell
无日志
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure this bug has not already been reported.

**Comment by PANPINGLI** [comment]
我解决了问题，卸载的不干净，系统有残留文件，给大家一个参考，用cleanmymac卸载软件 可以删除残留项目

**Comment by kaes1a** [comment]
m2 Pro macbook
我是新安装0.1.3就闪退

**Comment by PANPINGLI** [comment]
> m2 Pro macbook 我是新安装0.1.3就闪退

把之前的版本卸载干净，系统有缓存，所以会闪退 ，正常现象的

**Comment by cooaer** [comment]
@PANPINGLI 请问你还记得删除了什么文件？具体路径是什么？我也遇到了同样的问题，但是cleanmymac没有找到残留项目！

**Comment by cooaer** [comment]
仍然没有找到闪退的原因，但是我自己编了版本，可以正常运行！

**Comment by kaes1a** [comment]
> > m2 Pro macbook 我是新安装0.1.3就闪退
> 
> 把之前的版本卸载干净，系统有缓存，所以会闪退 ，正常现象的

我是全新安装的 一次都没安装过
