### ISSUE TITLE
运行程序时提示无法定位程序输入点 GetHostNameW 于动态链接库 WS2_32.dll 上

### ISSUE THREAD

**Issue by xueli12** [Xmarmalade/alisthelper#23]
### What is expected?

win7系统下运行程序时提示无法定位程序输入点 GetHostNameW 于动态链接库 WS2_32.dll 上

### What is actually happening?

win7系统下运行程序时提示无法定位程序输入点 GetHostNameW 于动态链接库 WS2_32.dll 上

### What version of our software are you running?

0.1.3

### Platform information

win7

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure this bug has not already been reported.

**Comment by Xmarmalade** [comment]
https://github.com/dart-lang/sdk/commit/b4479abeec6329263ab60c39b0f15d691a46fea3
这是来源于dart的问题

**Comment by Xmarmalade** [comment]
尝试在 [v0.1.4](https://github.com/Xmarmalade/alisthelper/releases/tag/v0.1.4) d73ae05fb2da2756a1a3860bb38e834ee3d9851d 修复
