### ISSUE TITLE
macos 14Beta版(23A5337a) 打开闪退

### ISSUE THREAD

**Issue by sad-castle** [Xmarmalade/alisthelper#24]
### What is expected?

升级到14的beta版以后，打开 alisthelper就闪退，无法正常使用。己经尝试卸载重新下载安装alisthelper，闪退后活动监视器里没有alist和alisthelper的进程

### What is actually happening?

闪退无法打开 

### What version of our software are you running?

alisthelper 0.1.2 / alist  3.27.0

### Platform information

macos 14 23A5337a

### Additional info

```shell
不好意思不知道如何提取 log
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure this bug has not already been reported.

**Comment by Xmarmalade** [comment]
https://github.com/Xmarmalade/alisthelper/issues
尝试清理缓存

**Comment by wowdd1** [comment]
mac 13 一样闪退
