### ISSUE TITLE
无法打开AlistHelper主界面

### ISSUE THREAD

**Issue by laisc7301** [Xmarmalade/alisthelper#26]
### 软件期望的结果是什么？

打开AlistHelper主界面

### 实际发生了什么？

![微信截图_20230915052726](https://github.com/Xmarmalade/alisthelper/assets/16506913/0693b1a8-de55-4cd8-bbe7-241f3bea011c)

任务栏可以显示AlistHelper的图标，但是点击后没有反应，打不开主界面。

localhost:5244页面可以打开，并且没有任何问题。

### 您运行的是我们的哪个版本的软件？

AlistHelper v0.1.3  Alist v3.27.0

### 平台信息

Win11 22H2

### 附加信息

```shell
无
```

### 这不是重复的问题

- [x] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
你的配置文件被损坏了，备份后删除

**Comment by laisc7301** [comment]
> 你的配置文件被损坏了，备份后删除 `%appdata%\dev.xmarmalade.alisthelper\alisthelper\shared_preferences.json`

问题解决了，谢谢

**Comment by jinfnfu** [comment]
我也遇到了这个问题，请问详细的解决步骤是啥

**Comment by dhies23** [comment]
> 我也遇到了这个问题，请问详细的解决步骤是啥

就是如上  去%appdata%\dev.xmarmalade.alisthelper\alisthelper    目录删除 shared_preferences.json就行了。然后关闭后台重新启动alisthelper

**Comment by mctz** [comment]
我删除了shared_preferences.json，还是无法启动
![image](https://github.com/Xmarmalade/alisthelper/assets/14092740/3167ed3b-ae88-4369-bc59-696438dea270)

**Comment by EchoAurora** [comment]
删掉后还是无法打开AlistHelper界面，右下角任务栏找不到图标，但是localhost:5244可以正常使用
