### ISSUE TITLE
更新时添加镜像加速

### ISSUE THREAD

**Issue by free-150** [Xmarmalade/alisthelper#27]
### 这是一个什么样的功能？

现在下载更新文件alist时太慢了，请添加镜像

### 这个功能可以解决什么问题？

下载慢，墙的问题。

### 这不是重复的功能请求或与 Alist Helper 本身无关的功能请求。

- [X] 我已经搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues)，以确保这不是一个重复的功能请求或与Alist Helper本身无关的功能请求。

### 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

- [X] 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

**Comment by Xmarmalade** [comment]
下载速度慢和alisthelper无关

**Comment by free-150** [comment]
加个 https://ghproxy.com/
