### ISSUE TITLE
打开白屏

### ISSUE THREAD

**Issue by JunXiaoRuo** [Xmarmalade/alisthelper#28]
### 软件期望的结果是什么？

正常

### 实际发生了什么？

白屏
![image](https://github.com/Xmarmalade/alisthelper/assets/47996900/fad0a2e2-dc8a-436d-9077-330bc3bfd350)
第一次双击没反应，但是任务管理器出现了进程，第二次双击如图所示

### 您运行的是我们的哪个版本的软件？

0.1.1

### 平台信息

windows 7

### 附加信息

```shell
无
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
微软已经停止了对windows7的支持，我也没有办法排查windows7的问题
