### ISSUE TITLE
登录以访问站点

### ISSUE THREAD

**Issue by Rockney99** [Xmarmalade/alisthelper#29]
### What is expected?

![image](https://github.com/Xmarmalade/alisthelper/assets/42824224/6a009253-987c-4b40-8953-c58f0ec62d1c)
这是什么 账号密码正确登录不上

### What is actually happening?

1

### What version of our software are you running?

1.64.0

### Platform information

Windows10

### Additional info

```shell
1
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure this bug has not already been reported.

**Comment by Xmarmalade** [comment]
无关问题，alisthelper只会打开`http://localhost:port/`，建议检查其他进程干扰或提供更多信息

**Comment by Rockney99** [comment]
已解决！谢谢  目前有一个问题尝试多次未解决你能帮忙看一下吗

**Comment by Rockney99** [comment]
![image](https://github.com/Xmarmalade/alisthelper/assets/42824224/663c3725-aee2-42f3-abee-f9efb6401fda)
![image](https://github.com/Xmarmalade/alisthelper/assets/42824224/28ed3cf2-28bc-4eb1-8441-a34fff180be4)
![image](https://github.com/Xmarmalade/alisthelper/assets/42824224/6033d66b-f206-4d5f-a51f-b4ce3fdfab1d)

**Comment by Rockney99** [comment]
![image](https://github.com/Xmarmalade/alisthelper/assets/42824224/3439b954-ddec-42f8-8eba-54a48691a8ce)
![image](https://github.com/Xmarmalade/alisthelper/assets/42824224/657b170b-6947-4ab0-98bb-20c87f662f2e)

**Comment by Xmarmalade** [comment]
你的端口和路径都是错的，建议 **_仔细阅读文档_**
![image](https://github.com/Xmarmalade/alisthelper/assets/16839488/ebe097ea-dff7-4453-a0ab-d90edaf022a5)

**Comment by Rockney99** [comment]
蚌埠住了 我看B站视频这样设置的 不行然后我自己又弄了好久都不行

**Comment by Xmarmalade** [comment]
rclone只是将AList公开的WebDAV映射为本地磁盘，可以仔细看看[AList文档中关于WebDAV的介绍](https://alist.nn.ci/zh/guide/webdav.html)，如果你需要逐步指导，请考虑赞助
