### ISSUE TITLE
点击 挂载 就闪退

### ISSUE THREAD

**Issue by sad-castle** [Xmarmalade/alisthelper#30]
### 软件期望的结果是什么？

点击挂载直接闪退

### 实际发生了什么？

点击挂载直接闪退

### 您运行的是我们的哪个版本的软件？

0.1.4

### 平台信息

macos 14.0 

### 附加信息

```shell
m1芯片
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
对应的文件夹缺失rclone，另外对于macOS的所有功能我均未参与测试
