### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by huameiwei-vc** [Xmarmalade/alisthelper#31]
### 软件期望的结果是什么？

修复一下

### 实际发生了什么？

打开后，自动安装闪退，启动闪退，后面直接打不开了。。。。

### 您运行的是我们的哪个版本的软件？

alisthelper 09.50.24

### 平台信息

macOS Ventura 13.6

### 附加信息

```shell
希望能修复一下，小白看到能自动安装，别提多高兴。。
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
自动安装未在macOS实际测试，由于我没有mac设备，还请手动安装

**Comment by jerrybeing** [comment]
我也是同样的系统 黑苹果  也闪退
