### ISSUE TITLE
打开了某个功能后，无法启动图形界面

### ISSUE THREAD

**Issue by a85418425** [Xmarmalade/alisthelper#32]
### 软件期望的结果是什么？

能正常打开图形界面

### 实际发生了什么？

目前双击桌面图标后，只有托盘运行，但是没有界面显示

### 您运行的是我们的哪个版本的软件？

最新版

### 平台信息

Win11

### 附加信息

```shell
可能是挂载
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
Duplicate of https://github.com/Xmarmalade/alisthelper/issues/26
配置文件被损坏了，备份后删除`%appdata%\dev.xmarmalade.alisthelper\alisthelper\shared_preferences.json`

**Comment by kvinfowang** [comment]
> Duplicate of #26 配置文件被损坏了，备份后删除`%appdata%\dev.xmarmalade.alisthelper\alisthelper\shared_preferences.json`

win10最后一次更新后打不开图形界面。删除shared_preferences.json和重新安装都不行。
请大佬更新。

**Comment by Xmarmalade** [comment]
更新了相关依赖，在旧版本和更新依赖后的版本上均无法复现
