### ISSUE TITLE
rclone挂载不成功

### ISSUE THREAD

**Issue by MushyX** [Xmarmalade/alisthelper#34]
### 软件期望的结果是什么？

大佬，我在用0.1.4版本，真的很好用啊，但是里边的rclone挂载功能还是用不好。根据你的wiki文档配置后，最后一步“在设置中的Rclone启动参数列表中输入rclone mount example:/ W: ，点击保存即可开始挂载。”怎么弄都不成功，求指教 。

### 实际发生了什么？

![PixPin_2023-12-22_10-32-47](https://github.com/Xmarmalade/alisthelper/assets/154570654/0fc364a5-687f-4f21-8d28-15b64532596e)
![PixPin_2023-12-22_10-32-57](https://github.com/Xmarmalade/alisthelper/assets/154570654/c804d1ed-68db-40c2-9a26-4d79a8bfb31a)

### 您运行的是我们的哪个版本的软件？

0.1.4

### 平台信息

Win11

### 附加信息

```shell
暂无
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by MushyX** [comment]
winfsp已安装

**Comment by Xmarmalade** [comment]
移除所有参数，然后输入`rclone mount example:/ W:`

**Comment by MushyX** [comment]
谢谢大佬，已经按照你说的做了“移除所有参数，然后输入rclone mount example:/  W: ”，但还是没成功，显示：2023/12/28** 09:00:55 Failed to create file system for "example:/": didn't find section in config file

**Comment by Xmarmalade** [comment]
修改成你实际的配置

**Comment by XTsat** [comment]
> 谢谢大佬，已经按照你说的做了“移除所有参数，然后输入rclone mount example:/ W: ”，但还是没成功，显示：2023/12/28** 09:00:55 Failed to create file system for "example:/": didn't find section in config file

example是例子的意思
请更换成你自己取的名字
比如我的挂载是 `rclone mount Alist:/ Z:`

**Comment by molun** [comment]
昨晚我也尝试过，在Alist Helper中移除所有参数，安装实际写入 `rclone mount Aliyundrive:/ W:` 不成功，直接在shell中执行
`.\rclone mount Aliyundrive:/ W:`可以看到挂载盘符W:，但是打不开。今天在rclone中的mounts中成功挂载
![image](https://github.com/Xmarmalade/alisthelper/assets/23138506/88d38b4d-db7d-4a1b-8190-4f25ddd611a6)
![image](https://github.com/Xmarmalade/alisthelper/assets/23138506/65e9ac0c-d79d-4461-9caa-fdc5b65ad59b)
可以进行文件移动操作，但是打开图片文件会显示图片损坏无法正常打开。Alist Helper中查看到日志如下：
![image](https://github.com/Xmarmalade/alisthelper/assets/23138506/bf895a92-1b42-4da2-a612-25e4c5e54c13)
2024/01/09 09:01:33 ERROR : IO error: 403 Forbidden

**Comment by Xmarmalade** [comment]
> ERROR : IO error: 403 Forbidden
似乎是你的网盘配置出现了问题，建议从alist开始排查

**Comment by MushyX** [comment]
> > 谢谢大佬，已经按照你说的做了“移除所有参数，然后输入rclone mount example:/ W: ”，但还是没成功，显示：2023/12/28** 09:00:55 Failed to create file system for "example:/": didn't find section in config file
> 
> example是例子的意思 请更换成你自己取的名字 比如我的挂载是 `rclone mount Alist:/ Z:`

谢谢🙏，按这个方法，已配置成功！
