### ISSUE TITLE
Enhancing AlistHelper with Customisable Themes and User Profiles

### ISSUE THREAD

**Issue by yihong1120** [Xmarmalade/alisthelper#35]
### What feature is it?

I would like to suggest the introduction of customisable themes and user profiles within the AlistHelper application. This feature would allow users to personalise the visual aspects of the app according to their preferences, including but not limited to colour schemes, font styles, and layout configurations. Additionally, the ability to create and switch between user profiles would enable multiple individuals to use the app on the same device while maintaining their unique settings and preferences.

### What problem does this feature solve?

The primary problem this feature addresses is the lack of personalisation and individual user experience within AlistHelper. Users who share the application on a single device must contend with a one-size-fits-all interface, which may not cater to their specific visual or organisational preferences. By implementing customisable themes and user profiles, AlistHelper can enhance user satisfaction by providing a more tailored and personal experience. This would not only improve the usability of the app for individuals but also make it more accommodating for shared use scenarios.

### Additional description

The implementation of this feature could involve the creation of a 'Themes and Profiles' section within the app settings. Here, users could select from a range of pre-defined themes or create their own by choosing specific colours and fonts. For user profiles, the ability to save and name different profiles would allow for quick switching and a more seamless transition between users.

I believe this enhancement would significantly contribute to the user-friendliness and appeal of AlistHelper, potentially attracting a broader user base and increasing overall engagement with the application.

Thank you for considering this proposal. I am looking forward to your thoughts and feedback on this potential addition to AlistHelper.

Best regards,
yihong1120

### This is not a duplicate feature request or a feature request unrelated to Alist Helper itself.

- [X] I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure This is not a duplicate feature request or a feature request unrelated to Alist Helper itself.

### I want to support Alist Helper and I have donated / sponsored Alist Helper

- [X] I want to support Alist Helper and I have donated / sponsored to Alist Helper

**Comment by Xmarmalade** [comment]
Please don't abuse AIGC for irrelevant issues, thanks!
