### ISSUE TITLE
如何添加多个网盘？

### ISSUE THREAD

**Issue by silas6012** [Xmarmalade/alisthelper#36]
### 这是一个什么样的功能？

在alisthelp的rclone启动参数列表里面，如何mount多个网盘？我添加第一个mount成功了，接着想添加另一个mount，结果没有成功。请问怎样做才能添加第二个网盘？如果想同时mount两个及以上的网盘，rclone启动参数列表接受怎样的格式？

### 这个功能可以解决什么问题？

mount多个网盘

### 这不是重复的功能请求或与 Alist Helper 本身无关的功能请求。

- [x] 我已经搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues)，以确保这不是一个重复的功能请求或与Alist Helper本身无关的功能请求。

### 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

- [ ] 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

**Comment by Xmarmalade** [comment]
不支持同时运行多个rclone，请在rclone中挂载alist的所有网盘
