### ISSUE TITLE
打开web-ui后页面空白

### ISSUE THREAD

**Issue by a85418425** [Xmarmalade/alisthelper#39]
### 软件期望的结果是什么？

期望得到解决
现在打开web-ui管理界面，无法正常显示，白屏
[图片.zip](https://github.com/Xmarmalade/alisthelper/files/14442520/default.zip)

### 实际发生了什么？

打开后台管理地址是白屏，什么都没显示

### 您运行的是我们的哪个版本的软件？

最新版

### 平台信息

Win11

### 附加信息

```shell

**Comment by Xmarmalade** [comment]
现有的内容无法定位问题原因，此外你的图片没有上传成功，请提交更多信息

**Comment by a85418425** [comment]
![1](https://github.com/Xmarmalade/alisthelper/assets/77822042/6f02d3af-da93-4bd2-9466-e6e6aa500d6a)
![2](https://github.com/Xmarmalade/alisthelper/assets/77822042/ff8d66ad-f692-4eb3-a91b-36b9e86e1bfb)

**Comment by Xmarmalade** [comment]
使用localhost:5244或者直接点击打开Web
GUI

**Comment by a85418425** [comment]
> 使用localhost:5244或者直接点击打开Web GUI

点击web-ui按钮打开就是空白的，尝试通过ip+端口号的形式打开也是不行的。

**Comment by Xmarmalade** [comment]
我不能复现这个问题，建议使用命令行单独启动alist进行测试，如果在命令行下启动也是白屏，则说明是无关问题。请向alist反馈或获取帮助

**Comment by a85418425** [comment]
AList打开空白的 进入后台后台 全局 自定义头部里面换一下

<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
换成这个阿里的

<script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
直接删了也可以，但是可能会导致其他人访问时候浏览器如果不兼容会打不开

不知道怎么进后台的 https://域名/@manage

**Comment by a85418425** [comment]
已经解决
