### ISSUE TITLE
Alisthelper界面不见了

### ISSUE THREAD

**Issue by xxxtentacion1379** [Xmarmalade/alisthelper#42]
### What is expected?

希望界面恢复正常，能配置alist

### What is actually happening?

想调整alist参数时，有一天突然发现alisthelper界面不见了，使用卸载程序卸载后，且删除对应文件夹之后，release重新下载安装包安装，还是打不开界面，但是由于我设置了开机自启动alist服务，所以alist服务工作正常，但是调不了设置，参数之类的。

### What version of our software are you running?

V0.1.4

### Platform information

Windows 11 22H2

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure this bug has not already been reported.

**Comment by BestSumy** [comment]
不知道你是不是设置过自定义桌面缩放
如果是的话，找到%appdata%\dev.xmarmalade.alisthelper\alisthelper\shared_preferences.json,备份一下，删除原来的文件并强制推出软件
然后呢用记事本打开备份的文件，删除
"flutter.ah_window_offset_x":。。。,"flutter.ah_window_offset_y":。。。,"flutter.ah_window_height":。。。,"flutter.ah_window_width":。。。

**Comment by xxxtentacion1379** [comment]
> 不知道你是不是设置过自定义桌面缩放 如果是的话，找到%appdata%\dev.xmarmalade.alisthelper\alisthelper\shared_preferences.json,备份一下，删除原来的文件并强制推出软件 然后呢用记事本打开备份的文件，删除 "flutter.ah_window_offset_x":。。。,"flutter.ah_window_offset_y":。。。,"flutter.ah_window_height":。。。,"flutter.ah_window_width":。。。

修改后出现界面了，谢谢你！

**Comment by BestSumy** [comment]
客气我也是看之前别人告诉的解决方案，不过如果只是删除文件会导致所有保存的配置消失

**Comment by ChenBlue067** [comment]
为什么我删除之后 我的helper打开主界面变成空白了

**Comment by ChenBlue067** [comment]
![Uploading Snipaste_2024-10-20_16-22-30.png…]()

**Comment by ChenBlue067** [comment]
![Uploading Snipaste_2024-10-20_16-22-30.png…]()

**Comment by cai19860307** [comment]
你好，我把挂载的A盘文件复制到B盘文件里面，但是A盘文件超过了2G，就会报错，这个问题怎么解决
