### ISSUE TITLE
可以设置rclone工作目录么

### ISSUE THREAD

**Issue by cnxv** [Xmarmalade/alisthelper#43]
### 这是一个什么样的功能？

指定rclone工作目录

### 这个功能可以解决什么问题？

指定rclone工作目录

### 额外描述

指定rclone工作目录

### 这不是重复的功能请求或与 Alist Helper 本身无关的功能请求。

- [X] 我已经搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues)，以确保这不是一个重复的功能请求或与Alist Helper本身无关的功能请求。

### 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

- [ ] 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

**Comment by Xmarmalade** [comment]
已添加 2483b3fbc1c3fca2b3882cb126775aed2fc651c1
