### ISSUE TITLE
alist helper打开无界面，修改后界面为空白

### ISSUE THREAD

**Issue by EricQ521** [Xmarmalade/alisthelper#44]
### 软件期望的结果是什么？

界面不在空白

### 实际发生了什么？

修改了一项文件：shared_preferences.json以打开alist界面——“flutter.ah_window_offset_x”：。。。，“flutter.ah_window_offset_y”：。。。，“flutter.ah_window_height”：。。。，“flutter.ah_window_width”：。。。
但最后打开了却是空白的界面

### 您运行的是我们的哪个版本的软件？

0.1.5

### 平台信息

版本	Windows 11 家庭中文版 版本	23H2  操作系统版本	22631.3235 体验	Windows Feature Experience Pack 1000.22687.1000.0

### 附加信息

```shell
无
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by BestSumy** [comment]
那我建议你删除这个jason文件，卸载并重装

**Comment by king9862520** [comment]
我也遇到了这个问题而且重装依然无效

**Comment by king9862520** [comment]
然后我尝试下载压缩包打开   还是一样的空白
![Uploading 微信图片_20240330213637.png…]()

**Comment by EricQ521** [comment]
好像将所有有关alist的文件删掉再重装就可以了

**Comment by Soulize** [comment]
遇到了同样的问题，窗口无法显示，卸载重装依然如此

**Comment by ChenBlue067** [comment]
我也遇到相同问题
