### ISSUE TITLE
Mac版 点击“打开Web GUI”按钮无反应

### ISSUE THREAD

**Issue by PrinSoul** [Xmarmalade/alisthelper#45]
### 软件期望的结果是什么？

修复 “打开Web GUI”按钮

### 实际发生了什么？

Mac版 点击界面中的 “打开Web GUI”按钮无反应

### 您运行的是我们的哪个版本的软件？

0.1.5

### 平台信息

MacOS 10.15.7

### 附加信息

```shell
使用环境：
MacOS 10.15.7
alist-darwin-amd64-v3.33
AlistHelper_v0.1.5_macos
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
请补充日志截图，和alist的confg.json

**Comment by Xmarmalade** [comment]
不能确定问题原因，我也无法复现这个错误，建议删除位于NSUserDefaults的配置文件

**Comment by AlphatoBeta** [comment]
win版v0.1.5也遇到这个问题了。点击“打开Web GUI”按钮无反应。初步推测问题出在这里：
INFO[2024-04-23 17:07:36] start HTTP server @ 0.0.0.0:5244             
INFO[2024-04-23 17:07:36] start S3 server @ 0.0.0.0:5246          
以前的版本本地链接我记得好像是127.0.0.1而不是0.0.0.0

**Comment by PrinSoul** [comment]
> win版v0.1.5也遇到这个问题了。点击“打开Web GUI”按钮无反应。初步推测问题出在这里： INFO[2024-04-23 17:07:36] start HTTP server @ 0.0.0.0:5244 INFO[2024-04-23 17:07:36] start S3 server @ 0.0.0.0:5246 以前的版本本地链接我记得好像是127.0.0.1而不是0.0.0.0

我Windows正常，是0.0.0.0
