### ISSUE TITLE
什么意思 

### ISSUE THREAD

**Issue by qian9008** [Xmarmalade/alisthelper#47]
### 软件期望的结果是什么？

如图 自动解析 很多行

### 实际发生了什么？

![image](https://github.com/Xmarmalade/alisthelper/assets/13587778/b22006ed-95bf-44d2-9cae-3e5ffdad5932)

### 您运行的是我们的哪个版本的软件？

最新

### 平台信息

win10

### 附加信息

```shell
原理不明 rclone.config 都不需要填写是怎么连接alist的webdav的
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
无关问题 自行查看wiki
