### ISSUE TITLE
[功能建议] 添加Http代理

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [Xmarmalade/alisthelper#5]
刚开始使用 Alist，很快就遇到了梯子问题和其它一些疑难杂症
虽然问题[解决了](https://github.com/alist-org/alist/discussions/4363) ，但是觉得新建三个文件来来回回的有点麻烦了，干脆写个小脚本好了，顺便实现托盘／启停／显示标准输出啥的．
突然想起前几天不是在小众论坛看到过一个 Alist 的 GUI 吗？直接跑去跟作者提 issue 当伸手党不就好啦
![图片](https://github.com/iiijam/alisthelper/assets/14090545/9d8ecaeb-fd99-4107-ba71-5bce6d27ca78)

顺便建议 AlistHelper 在检测到一些报错输出的时候，可以在 GUI 里提供一个简易的快速解答比如[这样](https://anwen-anyi.github.io/index/07-wenti.html)．甚至直接帮助用户修改配置，比如百度网盘下载大于 20mb 的文件报错，就打开 Alist 的「web 代理」设置

**Comment by LakeishaKowalczyk** [comment]
@iiijam 
我觉得为 Alist 单独配置代理是有必要的，很多用户不喜欢全局的代理

**Comment by iiijam** [comment]
已在https://github.com/iiijam/alisthelper/commit/830c47f34d59e462fa8d618059374f1e99e60b5e中添加，

下面是在测试环境中的效果：
![image](https://github.com/iiijam/alisthelper/assets/16839488/862fd52b-b815-4f70-b06c-70bdb628ba90)
![image](https://github.com/iiijam/alisthelper/assets/16839488/495d1290-7777-4819-b472-56c9f8083d9d)


暂时不会更新版本，如您急需此功能，可以自行参照workflow构建，顺便给这个项目点个star或是给我提供支持

**Comment by Xmarmalade** [comment]
已发布[v0.0.3](https://github.com/Xmarmalade/alisthelper/releases/tag/v0.0.3)
