### ISSUE TITLE
m1芯片os14.4.1无法使用，闪退，没有任何反应

### ISSUE THREAD

**Issue by yuhang616** [Xmarmalade/alisthelper#52]
### What is expected?

修复软件，提供使用说明

### What is actually happening?

m1芯片14.4.1系统双击打开没有任何反应，什么都不显示

### What version of our software are you running?

AlistHelper_v0.1.5_macos

### Platform information

os14.4.1

### Additional info

```shell
m1芯片14.4.1系统双击打开没有任何反应，什么都不显示
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure this bug has not already been reported.

**Comment by earyantLe** [comment]
+1

**Comment by zcl0129** [comment]
出现同样的问题尚且没有解决
macosventurs13.6.7

m1芯片

**Comment by Xmarmalade** [comment]
Maintainer needed for the macOS part of the code. No new macOS-related changes will be accepted until volunteers.
