### ISSUE TITLE
是否可以将Web GUI集成到软件的主界面

### ISSUE THREAD

**Issue by xurdy** [Xmarmalade/alisthelper#61]
### 这是一个什么样的功能？

是否可以将Web GUI集成到软件的主界面，以进一步加强软件的整体感，方便操作

### 这个功能可以解决什么问题？

减少在软件主体与web UI 之间来回切换的问题

### 这不是重复的功能请求或与 Alist Helper 本身无关的功能请求。

- [X] 我已经搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues)，以确保这不是一个重复的功能请求或与Alist Helper本身无关的功能请求。

### 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

- [ ] 我想支持 Alist Helper，我已经捐赠/赞助了 Alist Helper

**Comment by Xmarmalade** [comment]
如果需要加入web组件，则需要为平台嵌入Webview2/CEF，这对于应用程序的性能/体积会造成较大的问题
