### ISSUE TITLE
win7 64系统上无法定位程序输入点 GetHostNameW 于动态链接库 WS2_32.dll

### ISSUE THREAD

**Issue by dujiaoshu** [Xmarmalade/alisthelper#63]
### 软件期望的结果是什么？

希望最新版也能一直支持win7系统

### 实际发生了什么？

AlistHelper从0.1.5版本不支持win7系统运行了，0.1.4版本支持win7系统但没有挂在rclone功能。经过测试，替换除了主程序之外的其他所有文件，可以达到保留新功能并且能在wiin7系统运行的目的。

### 您运行的是我们的哪个版本的软件？

0.1.5

### 平台信息

win7 专业版 service pack 1

### 附加信息

```shell
无
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by dujiaoshu** [comment]
刚刚发现，如此替换之后功能是少了一点，缺少了rclone的路径设置部分。所以还是得等最新版本的支持

**Comment by Xmarmalade** [comment]
Flutter在3.19版本后移除了对Windows7的支持，你可以尝试fork后调整[pubspec.yaml](https://github.com/Xmarmalade/alisthelper/blob/master/pubspec.yaml)降级Flutter和依赖关系尝试运行，但不能保证也无法提供对windows7的可用性支持
