### ISSUE TITLE
界面无法打开（已解决）

### ISSUE THREAD

**Issue by WilsonLi678** [Xmarmalade/alisthelper#64]
### 软件期望的结果是什么？

在后台模式下无法打开界面 重新下载后安装问题依然存在
![微信图片_20241113095132](https://github.com/user-attachments/assets/8ede3145-aeeb-4615-9d00-527f4293ecee)

### 实际发生了什么？

正常使用了两个月 这几天出现打不开的情况 重新安装后依旧 

### 您运行的是我们的哪个版本的软件？

0.15

### 平台信息

win11 22631.4317

### 附加信息

```shell
1
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
参考

https://github.com/Xmarmalade/alisthelper/issues/42#issuecomment-2016314326
