### ISSUE TITLE
挂载功能运行异常

### ISSUE THREAD

**Issue by dXrayb** [Xmarmalade/alisthelper#65]
### 软件期望的结果是什么？

挂载无法正常运行

### 实际发生了什么？

报错， ERROR : Error while fetching the latest release of Web GUI: Get "https://github.com/rclone/rclone-webui-react/releases/download/v2.0.5/currentbuild.zip": dial tcp 20.205.243.166:443: connectex: No connection could be made because the target machine actively refused it.
 11:12:38 NOTICE: Serving Web GUI

### 您运行的是我们的哪个版本的软件？

v0.1.5

### 平台信息

Windows 11 专业版 版本号 23H2 22631.4541 

### 附加信息

```shell
ERROR : Error reading tag file at C:\Users\xray\AppData\Local\rclone\webgui\tag 
ERROR : Error while fetching the latest release of Web GUI: Get "https://github.com/rclone/rclone-webui-react/releases/download/v2.0.5/currentbuild.zip": dial tcp 20.205.243.166:443: connectex: No connection could be made because the target machine actively refused it.
NOTICE: Serving Web GUI

打开后浏览器显示404 page not found。
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by dXrayb** [comment]
@Xmarmalade 直接关闭了什么原因，是程序问题还是环境问题导致的？

**Comment by Xmarmalade** [comment]
网络问题，自行解决
