### ISSUE TITLE
无法打开rclone gui

### ISSUE THREAD

**Issue by wangxiansheng1014** [Xmarmalade/alisthelper#67]
### 软件期望的结果是什么？

成功在网页端打开rclong gui

### 实际发生了什么？

网页端要求我输入账户密码，但是我从来没有设置过

### 您运行的是我们的哪个版本的软件？

Version 0.1.5 (9)

### 平台信息

Mac os 15.1.1 (24B91)

### 附加信息

```shell
辛苦作者大大解惑
```

### 这不是重复的问题

- [X] 我搜索了[现有问题](https://github.com/Xmarmalade/alisthelper/issues) 以确保此错误不是重复的。

**Comment by Xmarmalade** [comment]
若您是第一次使用AList，AList会初始化一个密码，您会在日志中看到类似于下面的输出内容：INFO[YYYY-MM-DD HH:MM:SS] Successfully created the admin user and the initial password is: 12abCDef 

这代表您的初始账户是admin 密码则是12abCDef（仅作示例使用，密码是随机生成的），请牢牢记住密码，丢失需要重置。
