### ISSUE TITLE
[Enhancement] 支持MacOS平台

### ISSUE THREAD

**Issue by ethanjtch** [Xmarmalade/alisthelper#7]
你好，

非常感谢你开发了AlistHelper，为我们不懂技术语言且没有私人服务器的人提供了巨大的便利。

希望可以开发Mac端，我就可以设置为自启动了。

再次感谢！

Ethan

**Comment by justincnn** [comment]
同期待mac版

**Comment by Xmarmalade** [comment]
你好，由于我没有mac设备，所以对macOS的开发调试较为困难，但是代码基本是兼容的

**Comment by Mrered** [comment]
同求macOS版本

**Comment by Mrered** [comment]
写好之后我愿意尝试为其添加Homebrew安装支持

**Comment by aLIEz-xue** [comment]
> 你好，由于我没有mac设备，所以对macOS的开发调试较为困难，但是代码基本是兼容的

大佬，有打包的教程吗，我想在我的M1上打包个DMG安装包

**Comment by aLIEz-xue** [comment]
> 你好，由于我没有mac设备，所以对macOS的开发调试较为困难，但是代码基本是兼容的

程序判断alist程序是写死的吗，必须有alist.exe才能识别出来是吗，Mac上的alist没有后缀名，好像程序判断不出来
<img width="900" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/a272cf9b-2589-428e-aba3-075565dfb8cc">

**Comment by Xmarmalade** [comment]
> > 你好，由于我没有mac设备，所以对macOS的开发调试较为困难，但是代码基本是兼容的
> 
> 程序判断alist程序是写死的吗，必须有alist.exe才能识别出来是吗，Mac上的alist没有后缀名，好像程序判断不出来 <img alt="image" width="900" src="https://user-images.githubusercontent.com/59567929/239740734-a272cf9b-2589-428e-aba3-075565dfb8cc.png">

你好，我推送了一个新提交，增加了对系统环境的判断，请验证一下是否可行！

**Comment by aLIEz-xue** [comment]
> > > 你好，由于我没有mac设备，所以对macOS的开发调试较为困难，但是代码基本是兼容的
> > 
> > 
> > 程序判断alist程序是写死的吗，必须有alist.exe才能识别出来是吗，Mac上的alist没有后缀名，好像程序判断不出来 <img alt="image" width="900" src="https://user-images.githubusercontent.com/59567929/239740734-a272cf9b-2589-428e-aba3-075565dfb8cc.png">
> 
> 你好，我推送了一个新提交，增加了对系统环境的判断，请验证一下是否可行！

可行，添加alist成功了，但是启动不了
<img width="825" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/27e069fd-3870-4126-8e8d-51575fac39ad">
下面这是直接用alist启动的
<img width="810" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/161e086f-9899-43b7-9578-446f98c3418d">

**Comment by Xmarmalade** [comment]
你试试把`lib\provider\alist_provider.dart`中的`startAlist()`(Line48)其中的代码进行修改为
```dart
// other code (Line 58)
    if (Platform.isWindows) {
      process = await Process.start(
        '$workingDirectory\\alist.exe',
        alistArgs,
        workingDirectory: workingDirectory,
        environment: envVars,
      );
    } else {
      process = await Process.start(
        '$workingDirectory/alist',
        alistArgs,
        workingDirectory: workingDirectory,
        environment: envVars,
      );
    }
// other code
```看看能否启动

**Comment by aLIEz-xue** [comment]
> 你试试把`lib\provider\alist_provider.dart`中的`startAlist()`(Line48)其中的代码进行修改为
> 
> ```dart
> // other code (Line 58)
>     if (Platform.isWindows) {
>       process = await Process.start(
>         '$workingDirectory\\alist.exe',
>         alistArgs,
>         workingDirectory: workingDirectory,
>         environment: envVars,
>       );
>     } else {
>       process = await Process.start(
>         '$workingDirectory/alist',
>         alistArgs,
>         workingDirectory: workingDirectory,
>         environment: envVars,
>       );
>     }
> // other code
> ```
> 
> 看看能否启动

不行，但是我应该找到原因了，前面读取到的‘/Volumes/Macintosh HD’影响了命令执行
<img width="810" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/46402682-bb98-4408-9400-2357b3310508">
<img width="825" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/768028fc-a3f0-47e6-9615-551cc417fda1">

**Comment by Xmarmalade** [comment]
你试试手动把前置的目录删除，看看能不能通过程序的检查，然后检查启动,关闭等操作是否可行

**Comment by Xmarmalade** [comment]
> 不行，但是我应该找到原因了，前面读取到的‘/Volumes/Macintosh HD’影响了命令执行

这个应该不对，导致这个的原因应该是Macintosh HD的空格被系统判定分开了

**Comment by aLIEz-xue** [comment]
> 似乎是权限问题，考虑到文档：
> 
> ```
> 授予程序执行权限：
> chmod +x alist
> ```
> 
> 试试授予Alist Helper完全磁盘访问权限 加入权限检查，如果没有权限则提醒
> 
> ```dart
>     if (Platform.isWindows) {
>       process = await Process.start(
>         '$workingDirectory\\alist.exe',
>         alistArgs,
>         workingDirectory: workingDirectory,
>         environment: envVars,
>       );
>     } else {
>       if (Platform.isMacOS || Platform.isLinux) {
>         var stat = await File('$workingDirectory/alist').stat();
>         bool canExecute = (stat.mode & 0x100) != 0;
>         if (!canExecute) {
>           addOutput('Please run: chmod +x alist');
>         }
>       }
>       process = await Process.start(
>         '$workingDirectory/alist',
>         alistArgs,
>         workingDirectory: workingDirectory,
>         environment: envVars,
>       );
>     }
> ```
> 
> 也有可能是沙盒问题 [tekartik/process_run.dart#3](https://github.com/tekartik/process_run.dart/issues/3) https://pub.dev/documentation/process_run/latest/ 移除沙盒还可以让程序自启

可以了，关闭沙盒就行了，谢谢大佬，我再看看有没有其他问题，还有就是怎么打包成 dmg和app呀，我没打包过flutter

**Comment by Xmarmalade** [comment]
flutter build macos
https://docs.flutter.dev/deployment/macos

**Comment by ethanjtch** [comment]
已经开始期待了 😁

**Comment by aLIEz-xue** [comment]
> 已经开始期待了 😁

打包成APP测试了几遍，自启动软件和自启动alist都没什么问题，管理员信息、版本信息和检查更新点击会闪退，同时没有最小化菜单栏的功能，关闭alisthelper就直接关闭了（不影响alist），所以某种意义上来说也无所谓。

**Comment by Xmarmalade** [comment]
> > 已经开始期待了 😁
> 
> 打包成APP测试了几遍，自启动软件和自启动alist都没什么问题，管理员信息、版本信息和检查更新点击会闪退，同时没有最小化菜单栏的功能，关闭alisthelper就直接关闭了（不影响alist），所以某种意义上来说也无所谓。

闪退应该是没改，我一会修一下；系统托盘的问题可以详细描述一下吗

**Comment by aLIEz-xue** [comment]
> 

就是alisthelper没有这上面的小图标，类似Windows上面的托盘图标吧，只有程序坞里的图标，点击关闭就是关闭了
<img width="1091" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/e1b191b1-aa6e-4ec7-94ba-1863266db14f">
<img width="340" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/13902a54-3065-4968-accc-9dc28e1d44f7">

**Comment by aLIEz-xue** [comment]
> 我推送了一些新代码，其中包含：
> 
> * (macOS) 取消“关闭即退出”
> * (macOS) 禁用沙盒，允许联网
> * 修复了错误的alist进程调用
> * 在开机自启时可以隐藏
> 
> 请帮我测试一下是否有问题 @aLIEz-xue

测试了，这几个功能都没有问题，非常nice，管理员信息、版本信息和检查更新等功能也都没问题了，大佬牛呀

**Comment by Xmarmalade** [comment]
> > 我推荐了一些新代码，其中包含：
> > 
> > * (macOS) 取消“关闭即退出”
> > * (macOS) 禁止使用沙盒，允许联网
> > * 修复了错误的alist进入程序调整
> > * 在开机自启时可以隐藏
> > 
> > 请帮我测试一下是否有问题@aLIEz-xue
> 
> 测试了，这几个功能都没有问题，非常nice，管理员信息、版本信息和检查更新等功能也都没有问题了，大佬牛呀

现在点关闭还会完全退出吗；托盘还是用不了吗

**Comment by aLIEz-xue** [comment]
> > > 我推荐了一些新代码，其中包含：
> > > 
> > > * (macOS) 取消“关闭即退出”
> > > * (macOS) 禁止使用沙盒，允许联网
> > > * 修复了错误的alist进入程序调整
> > > * 在开机自启时可以隐藏
> > > 
> > > 请帮我测试一下是否有问题@aLIEz-xue
> > 
> > 
> > 测试了，这几个功能都没有问题，非常nice，管理员信息、版本信息和检查更新等功能也都没有问题了，大佬牛呀
> 
> 现在点关闭还会完全退出吗；托盘还是用不了吗

不会了，关闭后会隐藏到菜单栏里，菜单栏图标可用
<img width="112" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/ae8af73d-9b32-47a1-b2a2-b3bff9ce401c">

**Comment by Xmarmalade** [comment]
也就是说目前没有影响到macOS使用的bug了，那我稍后推一下新版本
