### ISSUE TITLE
可以支持 部署小雅 么？

### ISSUE THREAD

**Issue by muasays** [Xmarmalade/alisthelper#8]
请问后续可以支持部署 小雅alist么？http://alist.xiaoya.pro/     
https://www.pcoof.com/1734.html  有个叫 115小幸运的软件   也有这个功能，有PC版。

**Comment by Xmarmalade** [comment]
你好，我没有理解你的需求，本程序的初衷是方便地在本地运行alist

**Comment by Steven-Zhl** [comment]
似乎“小雅alist”是别人利用Alist建的一个资源站，是已经部署在其他服务器上的。
而这个项目是为了便于使用本地部署的Alist的。
所以估计是不行啦。
