### ISSUE TITLE
软件静默开机自启会在程序坞留下图标，点击无效

### ISSUE THREAD

**Issue by aLIEz-xue** [Xmarmalade/alisthelper#9]
### What is expected?

设置了静默启动，最好不在程序坞显示图标，仅在顶上菜单栏显示图标。

### What is actually happening?

<img width="240" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/ec88ceb0-e6e5-4a86-a730-e68f57297864">

必须在菜单栏图标右键选择隐藏，才可清除程序坞图标，否则只能右键关闭程序。

<img width="169" alt="image" src="https://github.com/Xmarmalade/alisthelper/assets/59567929/8f7e6d29-efd2-455e-8adb-10a7019ec31a">

### What version of our software are you running?

0.1.0

### Platform information

MacOS 13.4 (22F66)

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure this bug has not already been reported.

**Comment by Xmarmalade** [comment]
推送了新代码，试试行不行

**Comment by aLIEz-xue** [comment]
> 推送了新代码，试试行不行

没问题了，感谢大佬
